package cn.sunline.tiny.demo.mapper;
import org.apache.ibatis.session.SqlSessionFactory;
import org.mybatis.spring.SqlSessionFactoryBean;
import javax.sql.DataSource;
import java.io.File;
import java.util.ArrayList;
import java.util.List;import cn.sunline.tiny.core.Constant;
import cn.sunline.tiny.util.FileUtil;
import java.lang.reflect.Method;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;

/**
 * mapper Auxiliary class, ide dynamic generation
 */
public class TinyMapper {

	public static SqlSessionFactory getSqlSessionFactoryBean(DataSource dataSource){
		SqlSessionFactoryBean sqlSessionFactoryBean=new SqlSessionFactoryBean();
		try {
			sqlSessionFactoryBean.setDataSource(dataSource);
	        // 设置别名包（实体类）
	        sqlSessionFactoryBean.setTypeAliasesPackage("cn.sunline.tiny.demo.entity");
			String path =Constant.getWebPath()+File.separator+"mapper";
	        File mapperFold = new File(path);
	        if(!mapperFold.exists()) {
	        	return null;
	        }
			List<Resource> rs = new ArrayList<Resource>();
	        for(File file : mapperFold.listFiles()) {
	        	String name = file.getName();
	        	if(name.endsWith("xml")) {
	        		String xml = FileUtil.read(file);
	        		
	        		try {
	        			 Method getMapper = TinyMapper.class.getMethod("get"+name.substring(0,name.length()-4));
		        		 String s = (String) getMapper.invoke(null,null);
		        		 //System.out.println(s);
		        		 xml = xml.replace("</mapper>", s)+"</mapper>";
		        		 
	        		}catch(Exception ex) {
	        			
	        			//System.out.println(name+"Can not identify Mapper");
	        			 
	        		}
					ByteArrayResource bs = new ByteArrayResource(xml.getBytes("utf-8"),file.getPath());
	        		rs.add(bs);
	        	}
	        }
	        Resource[] rss = new Resource[rs.size()];
	        for(int i=0;i<rs.size();i++) {
	        	rss[i] = rs.get(i);
	        }
	      
	        //设置sql配置文件路径
	        sqlSessionFactoryBean.setMapperLocations(rss);
	        //-- 加载mybatis的全局配置文件  
	        Resource mybatisConfigXml = new PathMatchingResourcePatternResolver().getResource("classpath:mybatis-config.xml");
	        sqlSessionFactoryBean.setConfigLocation(mybatisConfigXml);			return sqlSessionFactoryBean.getObject();
		} catch (Exception e) {
			e.printStackTrace();
			throw new RuntimeException(e);
		}
	}

	public static String getCertificateMapper() {

		return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.tiny.demo.entity.Certificate\">"
				+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
				+"	<result column=\"userid\" jdbcType=\"VARCHAR\" property=\"userid\" />"
				+"	<result column=\"type\" jdbcType=\"VARCHAR\" property=\"type\" />"
				+"	<result column=\"cernumber\" jdbcType=\"VARCHAR\" property=\"cernumber\" />"
				+"	<result column=\"image\" jdbcType=\"VARCHAR\" property=\"image\" />"
				+"	<result column=\"space1\" jdbcType=\"VARCHAR\" property=\"space1\" />"
				+"	<result column=\"space2\" jdbcType=\"VARCHAR\" property=\"space2\" />"
				+"	<result column=\"space3\" jdbcType=\"VARCHAR\" property=\"space3\" />"
				+"	<result column=\"space4\" jdbcType=\"VARCHAR\" property=\"space4\" />"
				+"	<result column=\"space5\" jdbcType=\"VARCHAR\" property=\"space5\" />"
				+"	<result column=\"space6\" jdbcType=\"VARCHAR\" property=\"space6\" />"
			+"	</resultMap>"
			+"	<sql id=\"Base_Column_List\">"
				+"id,userid,type,cernumber,image,space1,space2,space3,space4,space5,space6"
			+"	</sql>"
			+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
				+"	select "
				+"	<include refid=\"Base_Column_List\" />"
				+"	from certificate"
				+"	where id = #{id,jdbcType=VARCHAR}"
			+"	</select>"
			+"	<delete id=\"deleteById\" parameterType=\"String\">"
				+"	delete from certificate"
				+"	where id = #{id,jdbcType=VARCHAR}"
			+"	</delete>"
			+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.tiny.demo.entity.Certificate\" useGeneratedKeys=\"true\">"
				+"	insert into certificate"
				+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
					+"<if test=\"id != null\">"
						+"id,"
					+"</if>"
					+"<if test=\"userid != null\">"
						+"userid,"
					+"</if>"
					+"<if test=\"type != null\">"
						+"type,"
					+"</if>"
					+"<if test=\"cernumber != null\">"
						+"cernumber,"
					+"</if>"
					+"<if test=\"image != null\">"
						+"image,"
					+"</if>"
					+"<if test=\"space1 != null\">"
						+"space1,"
					+"</if>"
					+"<if test=\"space2 != null\">"
						+"space2,"
					+"</if>"
					+"<if test=\"space3 != null\">"
						+"space3,"
					+"</if>"
					+"<if test=\"space4 != null\">"
						+"space4,"
					+"</if>"
					+"<if test=\"space5 != null\">"
						+"space5,"
					+"</if>"
					+"<if test=\"space6 != null\">"
						+"space6,"
					+"</if>"
				+"	</trim>"
				+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
					+"<if test=\"id != null\">"
						+"#{id,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"userid != null\">"
						+"#{userid,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"type != null\">"
						+"#{type,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"cernumber != null\">"
						+"#{cernumber,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"image != null\">"
						+"#{image,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space1 != null\">"
						+"#{space1,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space2 != null\">"
						+"#{space2,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space3 != null\">"
						+"#{space3,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space4 != null\">"
						+"#{space4,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space5 != null\">"
						+"#{space5,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space6 != null\">"
						+"#{space6,jdbcType=VARCHAR},"
					+"</if>"
				+"	</trim>"
			+"	</insert>"
			+"	<update id=\"updateById\" parameterType=\"cn.sunline.tiny.demo.entity.Certificate\">"
				+"	update certificate"
				+"	<set>"
				+"	<if test=\"userid != null\">"
					+"userid = #{userid,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"type != null\">"
					+"type = #{type,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"cernumber != null\">"
					+"cernumber = #{cernumber,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"image != null\">"
					+"image = #{image,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space1 != null\">"
					+"space1 = #{space1,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space2 != null\">"
					+"space2 = #{space2,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space3 != null\">"
					+"space3 = #{space3,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space4 != null\">"
					+"space4 = #{space4,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space5 != null\">"
					+"space5 = #{space5,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space6 != null\">"
					+"space6 = #{space6,jdbcType=VARCHAR},"
				+"	</if>"
				+"	</set>"
				+"	where id = #{id,jdbcType=VARCHAR}"
			+"	</update>";
			}
			public static String getUserMapper() {

		return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.tiny.demo.entity.User\">"
				+"	<id column=\"userid\" jdbcType=\"VARCHAR\" property=\"userid\" />"
				+"	<result column=\"pwd\" jdbcType=\"VARCHAR\" property=\"pwd\" />"
				+"	<result column=\"islock\" jdbcType=\"CHAR\" property=\"islock\" />"
				+"	<result column=\"facepwd\" jdbcType=\"VARCHAR\" property=\"facepwd\" />"
				+"	<result column=\"devid\" jdbcType=\"VARCHAR\" property=\"devid\" />"
				+"	<result column=\"creatdate\" jdbcType=\"DATE\" property=\"creatdate\" />"
				+"	<result column=\"modifydate\" jdbcType=\"DATE\" property=\"modifydate\" />"
				+"	<result column=\"mobile\" jdbcType=\"VARCHAR\" property=\"mobile\" />"
				+"	<result column=\"email\" jdbcType=\"VARCHAR\" property=\"email\" />"
				+"	<result column=\"device_taken\" jdbcType=\"VARCHAR\" property=\"deviceTaken\" />"
				+"	<result column=\"space1\" jdbcType=\"VARCHAR\" property=\"space1\" />"
				+"	<result column=\"space2\" jdbcType=\"VARCHAR\" property=\"space2\" />"
				+"	<result column=\"space3\" jdbcType=\"VARCHAR\" property=\"space3\" />"
				+"	<result column=\"space4\" jdbcType=\"VARCHAR\" property=\"space4\" />"
				+"	<result column=\"space5\" jdbcType=\"VARCHAR\" property=\"space5\" />"
				+"	<result column=\"space6\" jdbcType=\"VARCHAR\" property=\"space6\" />"
			+"	</resultMap>"
			+"	<sql id=\"Base_Column_List\">"
				+"userid,pwd,islock,facepwd,devid,creatdate,modifydate,mobile,email,device_taken,space1,space2,space3,space4,space5,space6"
			+"	</sql>"
			+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
				+"	select "
				+"	<include refid=\"Base_Column_List\" />"
				+"	from user"
				+"	where userid = #{userid,jdbcType=VARCHAR}"
			+"	</select>"
			+"	<delete id=\"deleteById\" parameterType=\"String\">"
				+"	delete from user"
				+"	where userid = #{userid,jdbcType=VARCHAR}"
			+"	</delete>"
			+"	<insert id=\"insert\" keyColumn=\"userid\" keyProperty=\"userid\" parameterType=\"cn.sunline.tiny.demo.entity.User\" useGeneratedKeys=\"true\">"
				+"	insert into user"
				+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
					+"<if test=\"userid != null\">"
						+"userid,"
					+"</if>"
					+"<if test=\"pwd != null\">"
						+"pwd,"
					+"</if>"
					+"<if test=\"islock != null\">"
						+"islock,"
					+"</if>"
					+"<if test=\"facepwd != null\">"
						+"facepwd,"
					+"</if>"
					+"<if test=\"devid != null\">"
						+"devid,"
					+"</if>"
					+"<if test=\"creatdate != null\">"
						+"creatdate,"
					+"</if>"
					+"<if test=\"modifydate != null\">"
						+"modifydate,"
					+"</if>"
					+"<if test=\"mobile != null\">"
						+"mobile,"
					+"</if>"
					+"<if test=\"email != null\">"
						+"email,"
					+"</if>"
					+"<if test=\"deviceTaken != null\">"
						+"device_taken,"
					+"</if>"
					+"<if test=\"space1 != null\">"
						+"space1,"
					+"</if>"
					+"<if test=\"space2 != null\">"
						+"space2,"
					+"</if>"
					+"<if test=\"space3 != null\">"
						+"space3,"
					+"</if>"
					+"<if test=\"space4 != null\">"
						+"space4,"
					+"</if>"
					+"<if test=\"space5 != null\">"
						+"space5,"
					+"</if>"
					+"<if test=\"space6 != null\">"
						+"space6,"
					+"</if>"
				+"	</trim>"
				+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
					+"<if test=\"userid != null\">"
						+"#{userid,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"pwd != null\">"
						+"#{pwd,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"islock != null\">"
						+"#{islock,jdbcType=CHAR},"
					+"</if>"
					+"<if test=\"facepwd != null\">"
						+"#{facepwd,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"devid != null\">"
						+"#{devid,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"creatdate != null\">"
						+"#{creatdate,jdbcType=DATE},"
					+"</if>"
					+"<if test=\"modifydate != null\">"
						+"#{modifydate,jdbcType=DATE},"
					+"</if>"
					+"<if test=\"mobile != null\">"
						+"#{mobile,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"email != null\">"
						+"#{email,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"deviceTaken != null\">"
						+"#{deviceTaken,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space1 != null\">"
						+"#{space1,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space2 != null\">"
						+"#{space2,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space3 != null\">"
						+"#{space3,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space4 != null\">"
						+"#{space4,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space5 != null\">"
						+"#{space5,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space6 != null\">"
						+"#{space6,jdbcType=VARCHAR},"
					+"</if>"
				+"	</trim>"
			+"	</insert>"
			+"	<update id=\"updateById\" parameterType=\"cn.sunline.tiny.demo.entity.User\">"
				+"	update user"
				+"	<set>"
				+"	<if test=\"pwd != null\">"
					+"pwd = #{pwd,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"islock != null\">"
					+"islock = #{islock,jdbcType=CHAR},"
				+"	</if>"
				+"	<if test=\"facepwd != null\">"
					+"facepwd = #{facepwd,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"devid != null\">"
					+"devid = #{devid,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"creatdate != null\">"
					+"creatdate = #{creatdate,jdbcType=DATE},"
				+"	</if>"
				+"	<if test=\"modifydate != null\">"
					+"modifydate = #{modifydate,jdbcType=DATE},"
				+"	</if>"
				+"	<if test=\"mobile != null\">"
					+"mobile = #{mobile,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"email != null\">"
					+"email = #{email,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"deviceTaken != null\">"
					+"device_taken = #{deviceTaken,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space1 != null\">"
					+"space1 = #{space1,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space2 != null\">"
					+"space2 = #{space2,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space3 != null\">"
					+"space3 = #{space3,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space4 != null\">"
					+"space4 = #{space4,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space5 != null\">"
					+"space5 = #{space5,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space6 != null\">"
					+"space6 = #{space6,jdbcType=VARCHAR},"
				+"	</if>"
				+"	</set>"
				+"	where userid = #{userid,jdbcType=VARCHAR}"
			+"	</update>";
			}
			public static String getUserTemplateMapper() {

		return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.tiny.demo.entity.UserTemplate\">"
				+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
				+"	<result column=\"devid\" jdbcType=\"VARCHAR\" property=\"devid\" />"
				+"	<result column=\"creatdate\" jdbcType=\"DATE\" property=\"creatdate\" />"
				+"	<result column=\"modifydate\" jdbcType=\"DATE\" property=\"modifydate\" />"
				+"	<result column=\"userid\" jdbcType=\"VARCHAR\" property=\"userid\" />"
				+"	<result column=\"mobile\" jdbcType=\"VARCHAR\" property=\"mobile\" />"
				+"	<result column=\"email\" jdbcType=\"VARCHAR\" property=\"email\" />"
				+"	<result column=\"device_taken\" jdbcType=\"VARCHAR\" property=\"deviceTaken\" />"
				+"	<result column=\"del\" jdbcType=\"CHAR\" property=\"del\" />"
				+"	<result column=\"space1\" jdbcType=\"VARCHAR\" property=\"space1\" />"
				+"	<result column=\"space2\" jdbcType=\"VARCHAR\" property=\"space2\" />"
				+"	<result column=\"space3\" jdbcType=\"VARCHAR\" property=\"space3\" />"
				+"	<result column=\"space4\" jdbcType=\"VARCHAR\" property=\"space4\" />"
				+"	<result column=\"space5\" jdbcType=\"VARCHAR\" property=\"space5\" />"
				+"	<result column=\"space6\" jdbcType=\"VARCHAR\" property=\"space6\" />"
			+"	</resultMap>"
			+"	<sql id=\"Base_Column_List\">"
				+"id,devid,creatdate,modifydate,userid,mobile,email,device_taken,del,space1,space2,space3,space4,space5,space6"
			+"	</sql>"
			+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
				+"	select "
				+"	<include refid=\"Base_Column_List\" />"
				+"	from user_template"
				+"	where id = #{id,jdbcType=VARCHAR}"
			+"	</select>"
			+"	<delete id=\"deleteById\" parameterType=\"String\">"
				+"	delete from user_template"
				+"	where id = #{id,jdbcType=VARCHAR}"
			+"	</delete>"
			+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.tiny.demo.entity.UserTemplate\" useGeneratedKeys=\"true\">"
				+"	insert into user_template"
				+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
					+"<if test=\"id != null\">"
						+"id,"
					+"</if>"
					+"<if test=\"devid != null\">"
						+"devid,"
					+"</if>"
					+"<if test=\"creatdate != null\">"
						+"creatdate,"
					+"</if>"
					+"<if test=\"modifydate != null\">"
						+"modifydate,"
					+"</if>"
					+"<if test=\"userid != null\">"
						+"userid,"
					+"</if>"
					+"<if test=\"mobile != null\">"
						+"mobile,"
					+"</if>"
					+"<if test=\"email != null\">"
						+"email,"
					+"</if>"
					+"<if test=\"deviceTaken != null\">"
						+"device_taken,"
					+"</if>"
					+"<if test=\"del != null\">"
						+"del,"
					+"</if>"
					+"<if test=\"space1 != null\">"
						+"space1,"
					+"</if>"
					+"<if test=\"space2 != null\">"
						+"space2,"
					+"</if>"
					+"<if test=\"space3 != null\">"
						+"space3,"
					+"</if>"
					+"<if test=\"space4 != null\">"
						+"space4,"
					+"</if>"
					+"<if test=\"space5 != null\">"
						+"space5,"
					+"</if>"
					+"<if test=\"space6 != null\">"
						+"space6,"
					+"</if>"
				+"	</trim>"
				+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
					+"<if test=\"id != null\">"
						+"#{id,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"devid != null\">"
						+"#{devid,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"creatdate != null\">"
						+"#{creatdate,jdbcType=DATE},"
					+"</if>"
					+"<if test=\"modifydate != null\">"
						+"#{modifydate,jdbcType=DATE},"
					+"</if>"
					+"<if test=\"userid != null\">"
						+"#{userid,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"mobile != null\">"
						+"#{mobile,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"email != null\">"
						+"#{email,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"deviceTaken != null\">"
						+"#{deviceTaken,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"del != null\">"
						+"#{del,jdbcType=CHAR},"
					+"</if>"
					+"<if test=\"space1 != null\">"
						+"#{space1,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space2 != null\">"
						+"#{space2,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space3 != null\">"
						+"#{space3,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space4 != null\">"
						+"#{space4,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space5 != null\">"
						+"#{space5,jdbcType=VARCHAR},"
					+"</if>"
					+"<if test=\"space6 != null\">"
						+"#{space6,jdbcType=VARCHAR},"
					+"</if>"
				+"	</trim>"
			+"	</insert>"
			+"	<update id=\"updateById\" parameterType=\"cn.sunline.tiny.demo.entity.UserTemplate\">"
				+"	update user_template"
				+"	<set>"
				+"	<if test=\"devid != null\">"
					+"devid = #{devid,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"creatdate != null\">"
					+"creatdate = #{creatdate,jdbcType=DATE},"
				+"	</if>"
				+"	<if test=\"modifydate != null\">"
					+"modifydate = #{modifydate,jdbcType=DATE},"
				+"	</if>"
				+"	<if test=\"userid != null\">"
					+"userid = #{userid,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"mobile != null\">"
					+"mobile = #{mobile,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"email != null\">"
					+"email = #{email,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"deviceTaken != null\">"
					+"device_taken = #{deviceTaken,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"del != null\">"
					+"del = #{del,jdbcType=CHAR},"
				+"	</if>"
				+"	<if test=\"space1 != null\">"
					+"space1 = #{space1,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space2 != null\">"
					+"space2 = #{space2,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space3 != null\">"
					+"space3 = #{space3,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space4 != null\">"
					+"space4 = #{space4,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space5 != null\">"
					+"space5 = #{space5,jdbcType=VARCHAR},"
				+"	</if>"
				+"	<if test=\"space6 != null\">"
					+"space6 = #{space6,jdbcType=VARCHAR},"
				+"	</if>"
				+"	</set>"
				+"	where id = #{id,jdbcType=VARCHAR}"
			+"	</update>";
			}
	public static String getAccountMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.tiny.demo.entity.Account\">"
		+"	<id column=\"accountid\" jdbcType=\"VARCHAR\" property=\"accountid\" />"
		+"	<result column=\"userid\" jdbcType=\"VARCHAR\" property=\"userid\" />"
		+"	<result column=\"productid\" jdbcType=\"VARCHAR\" property=\"productid\" />"
		+"	<result column=\"realp\" jdbcType=\"DOUBLE\" property=\"realp\" />"
		+"	<result column=\"creatdate\" jdbcType=\"DATE\" property=\"creatdate\" />"
		+"	<result column=\"modifydate\" jdbcType=\"DATE\" property=\"modifydate\" />"
		+"	<result column=\"issell\" jdbcType=\"CHAR\" property=\"issell\" />"
		+"	<result column=\"iscard\" jdbcType=\"CHAR\" property=\"iscard\" />"
		+"	<result column=\"space1\" jdbcType=\"VARCHAR\" property=\"space1\" />"
		+"	<result column=\"space2\" jdbcType=\"VARCHAR\" property=\"space2\" />"
		+"	<result column=\"space3\" jdbcType=\"VARCHAR\" property=\"space3\" />"
		+"	<result column=\"space4\" jdbcType=\"VARCHAR\" property=\"space4\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"accountid,userid,productid,realp,creatdate,modifydate,issell,iscard,space1,space2,space3,space4"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from account"
		+"	where accountid = #{accountid,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from account"
		+"	where accountid = #{accountid,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"accountid\" keyProperty=\"accountid\" parameterType=\"cn.sunline.tiny.demo.entity.Account\" useGeneratedKeys=\"true\">"
		+"	insert into account"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"accountid != null\">"
				+"accountid,"
			+"</if>"
			+"<if test=\"userid != null\">"
				+"userid,"
			+"</if>"
			+"<if test=\"productid != null\">"
				+"productid,"
			+"</if>"
			+"<if test=\"realp != null\">"
				+"realp,"
			+"</if>"
			+"<if test=\"creatdate != null\">"
				+"creatdate,"
			+"</if>"
			+"<if test=\"modifydate != null\">"
				+"modifydate,"
			+"</if>"
			+"<if test=\"issell != null\">"
				+"issell,"
			+"</if>"
			+"<if test=\"iscard != null\">"
				+"iscard,"
			+"</if>"
			+"<if test=\"space1 != null\">"
				+"space1,"
			+"</if>"
			+"<if test=\"space2 != null\">"
				+"space2,"
			+"</if>"
			+"<if test=\"space3 != null\">"
				+"space3,"
			+"</if>"
			+"<if test=\"space4 != null\">"
				+"space4,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"accountid != null\">"
				+"#{accountid,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"userid != null\">"
				+"#{userid,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"productid != null\">"
				+"#{productid,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"realp != null\">"
				+"#{realp,jdbcType=DOUBLE},"
			+"</if>"
			+"<if test=\"creatdate != null\">"
				+"#{creatdate,jdbcType=DATE},"
			+"</if>"
			+"<if test=\"modifydate != null\">"
				+"#{modifydate,jdbcType=DATE},"
			+"</if>"
			+"<if test=\"issell != null\">"
				+"#{issell,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"iscard != null\">"
				+"#{iscard,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"space1 != null\">"
				+"#{space1,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space2 != null\">"
				+"#{space2,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space3 != null\">"
				+"#{space3,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space4 != null\">"
				+"#{space4,jdbcType=VARCHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.tiny.demo.entity.Account\">"
		+"	update account"
		+"	<set>"
		+"	<if test=\"userid != null\">"
			+"userid = #{userid,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"productid != null\">"
			+"productid = #{productid,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"realp != null\">"
			+"realp = #{realp,jdbcType=DOUBLE},"
		+"	</if>"
		+"	<if test=\"creatdate != null\">"
			+"creatdate = #{creatdate,jdbcType=DATE},"
		+"	</if>"
		+"	<if test=\"modifydate != null\">"
			+"modifydate = #{modifydate,jdbcType=DATE},"
		+"	</if>"
		+"	<if test=\"issell != null\">"
			+"issell = #{issell,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"iscard != null\">"
			+"iscard = #{iscard,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"space1 != null\">"
			+"space1 = #{space1,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space2 != null\">"
			+"space2 = #{space2,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space3 != null\">"
			+"space3 = #{space3,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space4 != null\">"
			+"space4 = #{space4,jdbcType=VARCHAR},"
		+"	</if>"
		+"	</set>"
		+"	where accountid = #{accountid,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getBillMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.tiny.demo.entity.Bill\">"
		+"	<id column=\"billid\" jdbcType=\"VARCHAR\" property=\"billid\" />"
		+"	<result column=\"fundid\" jdbcType=\"VARCHAR\" property=\"fundid\" />"
		+"	<result column=\"serialnumber\" jdbcType=\"VARCHAR\" property=\"serialnumber\" />"
		+"	<result column=\"proname\" jdbcType=\"VARCHAR\" property=\"proname\" />"
		+"	<result column=\"proprice\" jdbcType=\"DOUBLE\" property=\"proprice\" />"
		+"	<result column=\"creatdate\" jdbcType=\"DATE\" property=\"creatdate\" />"
		+"	<result column=\"modifydate\" jdbcType=\"DATE\" property=\"modifydate\" />"
		+"	<result column=\"detail\" jdbcType=\"VARCHAR\" property=\"detail\" />"
		+"	<result column=\"state\" jdbcType=\"CHAR\" property=\"state\" />"
		+"	<result column=\"space1\" jdbcType=\"VARCHAR\" property=\"space1\" />"
		+"	<result column=\"space2\" jdbcType=\"VARCHAR\" property=\"space2\" />"
		+"	<result column=\"space3\" jdbcType=\"VARCHAR\" property=\"space3\" />"
		+"	<result column=\"space4\" jdbcType=\"VARCHAR\" property=\"space4\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"billid,fundid,serialnumber,proname,proprice,creatdate,modifydate,detail,state,space1,space2,space3,space4"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from bill"
		+"	where billid = #{billid,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from bill"
		+"	where billid = #{billid,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"billid\" keyProperty=\"billid\" parameterType=\"cn.sunline.tiny.demo.entity.Bill\" useGeneratedKeys=\"true\">"
		+"	insert into bill"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"billid != null\">"
				+"billid,"
			+"</if>"
			+"<if test=\"fundid != null\">"
				+"fundid,"
			+"</if>"
			+"<if test=\"serialnumber != null\">"
				+"serialnumber,"
			+"</if>"
			+"<if test=\"proname != null\">"
				+"proname,"
			+"</if>"
			+"<if test=\"proprice != null\">"
				+"proprice,"
			+"</if>"
			+"<if test=\"creatdate != null\">"
				+"creatdate,"
			+"</if>"
			+"<if test=\"modifydate != null\">"
				+"modifydate,"
			+"</if>"
			+"<if test=\"detail != null\">"
				+"detail,"
			+"</if>"
			+"<if test=\"state != null\">"
				+"state,"
			+"</if>"
			+"<if test=\"space1 != null\">"
				+"space1,"
			+"</if>"
			+"<if test=\"space2 != null\">"
				+"space2,"
			+"</if>"
			+"<if test=\"space3 != null\">"
				+"space3,"
			+"</if>"
			+"<if test=\"space4 != null\">"
				+"space4,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"billid != null\">"
				+"#{billid,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"fundid != null\">"
				+"#{fundid,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"serialnumber != null\">"
				+"#{serialnumber,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"proname != null\">"
				+"#{proname,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"proprice != null\">"
				+"#{proprice,jdbcType=DOUBLE},"
			+"</if>"
			+"<if test=\"creatdate != null\">"
				+"#{creatdate,jdbcType=DATE},"
			+"</if>"
			+"<if test=\"modifydate != null\">"
				+"#{modifydate,jdbcType=DATE},"
			+"</if>"
			+"<if test=\"detail != null\">"
				+"#{detail,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"state != null\">"
				+"#{state,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"space1 != null\">"
				+"#{space1,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space2 != null\">"
				+"#{space2,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space3 != null\">"
				+"#{space3,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space4 != null\">"
				+"#{space4,jdbcType=VARCHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.tiny.demo.entity.Bill\">"
		+"	update bill"
		+"	<set>"
		+"	<if test=\"fundid != null\">"
			+"fundid = #{fundid,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"serialnumber != null\">"
			+"serialnumber = #{serialnumber,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"proname != null\">"
			+"proname = #{proname,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"proprice != null\">"
			+"proprice = #{proprice,jdbcType=DOUBLE},"
		+"	</if>"
		+"	<if test=\"creatdate != null\">"
			+"creatdate = #{creatdate,jdbcType=DATE},"
		+"	</if>"
		+"	<if test=\"modifydate != null\">"
			+"modifydate = #{modifydate,jdbcType=DATE},"
		+"	</if>"
		+"	<if test=\"detail != null\">"
			+"detail = #{detail,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"state != null\">"
			+"state = #{state,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"space1 != null\">"
			+"space1 = #{space1,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space2 != null\">"
			+"space2 = #{space2,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space3 != null\">"
			+"space3 = #{space3,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space4 != null\">"
			+"space4 = #{space4,jdbcType=VARCHAR},"
		+"	</if>"
		+"	</set>"
		+"	where billid = #{billid,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getCardMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.tiny.demo.entity.Card\">"
		+"	<id column=\"cardid\" jdbcType=\"VARCHAR\" property=\"cardid\" />"
		+"	<result column=\"accountid\" jdbcType=\"VARCHAR\" property=\"accountid\" />"
		+"	<result column=\"cardnumber\" jdbcType=\"VARCHAR\" property=\"cardnumber\" />"
		+"	<result column=\"creatdate\" jdbcType=\"DATE\" property=\"creatdate\" />"
		+"	<result column=\"modifydate\" jdbcType=\"DATE\" property=\"modifydate\" />"
		+"	<result column=\"state\" jdbcType=\"CHAR\" property=\"state\" />"
		+"	<result column=\"space1\" jdbcType=\"VARCHAR\" property=\"space1\" />"
		+"	<result column=\"space2\" jdbcType=\"VARCHAR\" property=\"space2\" />"
		+"	<result column=\"space3\" jdbcType=\"VARCHAR\" property=\"space3\" />"
		+"	<result column=\"space4\" jdbcType=\"VARCHAR\" property=\"space4\" />"
		+"	<result column=\"space5\" jdbcType=\"VARCHAR\" property=\"space5\" />"
		+"	<result column=\"space6\" jdbcType=\"VARCHAR\" property=\"space6\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"cardid,accountid,cardnumber,creatdate,modifydate,state,space1,space2,space3,space4,space5,space6"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from card"
		+"	where cardid = #{cardid,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from card"
		+"	where cardid = #{cardid,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"cardid\" keyProperty=\"cardid\" parameterType=\"cn.sunline.tiny.demo.entity.Card\" useGeneratedKeys=\"true\">"
		+"	insert into card"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"cardid != null\">"
				+"cardid,"
			+"</if>"
			+"<if test=\"accountid != null\">"
				+"accountid,"
			+"</if>"
			+"<if test=\"cardnumber != null\">"
				+"cardnumber,"
			+"</if>"
			+"<if test=\"creatdate != null\">"
				+"creatdate,"
			+"</if>"
			+"<if test=\"modifydate != null\">"
				+"modifydate,"
			+"</if>"
			+"<if test=\"state != null\">"
				+"state,"
			+"</if>"
			+"<if test=\"space1 != null\">"
				+"space1,"
			+"</if>"
			+"<if test=\"space2 != null\">"
				+"space2,"
			+"</if>"
			+"<if test=\"space3 != null\">"
				+"space3,"
			+"</if>"
			+"<if test=\"space4 != null\">"
				+"space4,"
			+"</if>"
			+"<if test=\"space5 != null\">"
				+"space5,"
			+"</if>"
			+"<if test=\"space6 != null\">"
				+"space6,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"cardid != null\">"
				+"#{cardid,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"accountid != null\">"
				+"#{accountid,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"cardnumber != null\">"
				+"#{cardnumber,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"creatdate != null\">"
				+"#{creatdate,jdbcType=DATE},"
			+"</if>"
			+"<if test=\"modifydate != null\">"
				+"#{modifydate,jdbcType=DATE},"
			+"</if>"
			+"<if test=\"state != null\">"
				+"#{state,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"space1 != null\">"
				+"#{space1,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space2 != null\">"
				+"#{space2,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space3 != null\">"
				+"#{space3,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space4 != null\">"
				+"#{space4,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space5 != null\">"
				+"#{space5,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space6 != null\">"
				+"#{space6,jdbcType=VARCHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.tiny.demo.entity.Card\">"
		+"	update card"
		+"	<set>"
		+"	<if test=\"accountid != null\">"
			+"accountid = #{accountid,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"cardnumber != null\">"
			+"cardnumber = #{cardnumber,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"creatdate != null\">"
			+"creatdate = #{creatdate,jdbcType=DATE},"
		+"	</if>"
		+"	<if test=\"modifydate != null\">"
			+"modifydate = #{modifydate,jdbcType=DATE},"
		+"	</if>"
		+"	<if test=\"state != null\">"
			+"state = #{state,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"space1 != null\">"
			+"space1 = #{space1,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space2 != null\">"
			+"space2 = #{space2,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space3 != null\">"
			+"space3 = #{space3,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space4 != null\">"
			+"space4 = #{space4,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space5 != null\">"
			+"space5 = #{space5,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space6 != null\">"
			+"space6 = #{space6,jdbcType=VARCHAR},"
		+"	</if>"
		+"	</set>"
		+"	where cardid = #{cardid,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getFundMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.tiny.demo.entity.Fund\">"
		+"	<id column=\"fundid\" jdbcType=\"VARCHAR\" property=\"fundid\" />"
		+"	<result column=\"userid\" jdbcType=\"VARCHAR\" property=\"userid\" />"
		+"	<result column=\"total\" jdbcType=\"DOUBLE\" property=\"total\" />"
		+"	<result column=\"maxtransaction\" jdbcType=\"DOUBLE\" property=\"maxtransaction\" />"
		+"	<result column=\"creatdate\" jdbcType=\"DATE\" property=\"creatdate\" />"
		+"	<result column=\"modifydate\" jdbcType=\"DATE\" property=\"modifydate\" />"
		+"	<result column=\"space1\" jdbcType=\"VARCHAR\" property=\"space1\" />"
		+"	<result column=\"space2\" jdbcType=\"VARCHAR\" property=\"space2\" />"
		+"	<result column=\"space3\" jdbcType=\"VARCHAR\" property=\"space3\" />"
		+"	<result column=\"space4\" jdbcType=\"VARCHAR\" property=\"space4\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"fundid,userid,total,maxtransaction,creatdate,modifydate,space1,space2,space3,space4"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from fund"
		+"	where fundid = #{fundid,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from fund"
		+"	where fundid = #{fundid,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"fundid\" keyProperty=\"fundid\" parameterType=\"cn.sunline.tiny.demo.entity.Fund\" useGeneratedKeys=\"true\">"
		+"	insert into fund"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"fundid != null\">"
				+"fundid,"
			+"</if>"
			+"<if test=\"userid != null\">"
				+"userid,"
			+"</if>"
			+"<if test=\"total != null\">"
				+"total,"
			+"</if>"
			+"<if test=\"maxtransaction != null\">"
				+"maxtransaction,"
			+"</if>"
			+"<if test=\"creatdate != null\">"
				+"creatdate,"
			+"</if>"
			+"<if test=\"modifydate != null\">"
				+"modifydate,"
			+"</if>"
			+"<if test=\"space1 != null\">"
				+"space1,"
			+"</if>"
			+"<if test=\"space2 != null\">"
				+"space2,"
			+"</if>"
			+"<if test=\"space3 != null\">"
				+"space3,"
			+"</if>"
			+"<if test=\"space4 != null\">"
				+"space4,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"fundid != null\">"
				+"#{fundid,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"userid != null\">"
				+"#{userid,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"total != null\">"
				+"#{total,jdbcType=DOUBLE},"
			+"</if>"
			+"<if test=\"maxtransaction != null\">"
				+"#{maxtransaction,jdbcType=DOUBLE},"
			+"</if>"
			+"<if test=\"creatdate != null\">"
				+"#{creatdate,jdbcType=DATE},"
			+"</if>"
			+"<if test=\"modifydate != null\">"
				+"#{modifydate,jdbcType=DATE},"
			+"</if>"
			+"<if test=\"space1 != null\">"
				+"#{space1,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space2 != null\">"
				+"#{space2,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space3 != null\">"
				+"#{space3,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space4 != null\">"
				+"#{space4,jdbcType=VARCHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.tiny.demo.entity.Fund\">"
		+"	update fund"
		+"	<set>"
		+"	<if test=\"userid != null\">"
			+"userid = #{userid,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"total != null\">"
			+"total = #{total,jdbcType=DOUBLE},"
		+"	</if>"
		+"	<if test=\"maxtransaction != null\">"
			+"maxtransaction = #{maxtransaction,jdbcType=DOUBLE},"
		+"	</if>"
		+"	<if test=\"creatdate != null\">"
			+"creatdate = #{creatdate,jdbcType=DATE},"
		+"	</if>"
		+"	<if test=\"modifydate != null\">"
			+"modifydate = #{modifydate,jdbcType=DATE},"
		+"	</if>"
		+"	<if test=\"space1 != null\">"
			+"space1 = #{space1,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space2 != null\">"
			+"space2 = #{space2,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space3 != null\">"
			+"space3 = #{space3,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space4 != null\">"
			+"space4 = #{space4,jdbcType=VARCHAR},"
		+"	</if>"
		+"	</set>"
		+"	where fundid = #{fundid,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getProductMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.tiny.demo.entity.Product\">"
		+"	<id column=\"productid\" jdbcType=\"VARCHAR\" property=\"productid\" />"
		+"	<result column=\"name\" jdbcType=\"VARCHAR\" property=\"name\" />"
		+"	<result column=\"title\" jdbcType=\"VARCHAR\" property=\"title\" />"
		+"	<result column=\"creatdate\" jdbcType=\"DATE\" property=\"creatdate\" />"
		+"	<result column=\"modifydate\" jdbcType=\"DATE\" property=\"modifydate\" />"
		+"	<result column=\"saletotal\" jdbcType=\"DOUBLE\" property=\"saletotal\" />"
		+"	<result column=\"minpp\" jdbcType=\"DOUBLE\" property=\"minpp\" />"
		+"	<result column=\"maxpp\" jdbcType=\"DOUBLE\" property=\"maxpp\" />"
		+"	<result column=\"describe\" jdbcType=\"VARCHAR\" property=\"describe\" />"
		+"	<result column=\"rate\" jdbcType=\"DOUBLE\" property=\"rate\" />"
		+"	<result column=\"cyclicity\" jdbcType=\"VARCHAR\" property=\"cyclicity\" />"
		+"	<result column=\"state\" jdbcType=\"CHAR\" property=\"state\" />"
		+"	<result column=\"star\" jdbcType=\"DATE\" property=\"star\" />"
		+"	<result column=\"stop\" jdbcType=\"DATE\" property=\"stop\" />"
		+"	<result column=\"step\" jdbcType=\"VARCHAR\" property=\"step\" />"
		+"	<result column=\"space1\" jdbcType=\"VARCHAR\" property=\"space1\" />"
		+"	<result column=\"space2\" jdbcType=\"VARCHAR\" property=\"space2\" />"
		+"	<result column=\"space3\" jdbcType=\"VARCHAR\" property=\"space3\" />"
		+"	<result column=\"space4\" jdbcType=\"VARCHAR\" property=\"space4\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"productid,name,title,creatdate,modifydate,saletotal,minpp,maxpp,describe,rate,cyclicity,state,star,stop,step,space1,space2,space3,space4"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from product"
		+"	where productid = #{productid,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from product"
		+"	where productid = #{productid,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"productid\" keyProperty=\"productid\" parameterType=\"cn.sunline.tiny.demo.entity.Product\" useGeneratedKeys=\"true\">"
		+"	insert into product"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"productid != null\">"
				+"productid,"
			+"</if>"
			+"<if test=\"name != null\">"
				+"name,"
			+"</if>"
			+"<if test=\"title != null\">"
				+"title,"
			+"</if>"
			+"<if test=\"creatdate != null\">"
				+"creatdate,"
			+"</if>"
			+"<if test=\"modifydate != null\">"
				+"modifydate,"
			+"</if>"
			+"<if test=\"saletotal != null\">"
				+"saletotal,"
			+"</if>"
			+"<if test=\"minpp != null\">"
				+"minpp,"
			+"</if>"
			+"<if test=\"maxpp != null\">"
				+"maxpp,"
			+"</if>"
			+"<if test=\"describe != null\">"
				+"describe,"
			+"</if>"
			+"<if test=\"rate != null\">"
				+"rate,"
			+"</if>"
			+"<if test=\"cyclicity != null\">"
				+"cyclicity,"
			+"</if>"
			+"<if test=\"state != null\">"
				+"state,"
			+"</if>"
			+"<if test=\"star != null\">"
				+"star,"
			+"</if>"
			+"<if test=\"stop != null\">"
				+"stop,"
			+"</if>"
			+"<if test=\"step != null\">"
				+"step,"
			+"</if>"
			+"<if test=\"space1 != null\">"
				+"space1,"
			+"</if>"
			+"<if test=\"space2 != null\">"
				+"space2,"
			+"</if>"
			+"<if test=\"space3 != null\">"
				+"space3,"
			+"</if>"
			+"<if test=\"space4 != null\">"
				+"space4,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"productid != null\">"
				+"#{productid,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"name != null\">"
				+"#{name,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"title != null\">"
				+"#{title,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"creatdate != null\">"
				+"#{creatdate,jdbcType=DATE},"
			+"</if>"
			+"<if test=\"modifydate != null\">"
				+"#{modifydate,jdbcType=DATE},"
			+"</if>"
			+"<if test=\"saletotal != null\">"
				+"#{saletotal,jdbcType=DOUBLE},"
			+"</if>"
			+"<if test=\"minpp != null\">"
				+"#{minpp,jdbcType=DOUBLE},"
			+"</if>"
			+"<if test=\"maxpp != null\">"
				+"#{maxpp,jdbcType=DOUBLE},"
			+"</if>"
			+"<if test=\"describe != null\">"
				+"#{describe,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"rate != null\">"
				+"#{rate,jdbcType=DOUBLE},"
			+"</if>"
			+"<if test=\"cyclicity != null\">"
				+"#{cyclicity,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"state != null\">"
				+"#{state,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"star != null\">"
				+"#{star,jdbcType=DATE},"
			+"</if>"
			+"<if test=\"stop != null\">"
				+"#{stop,jdbcType=DATE},"
			+"</if>"
			+"<if test=\"step != null\">"
				+"#{step,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space1 != null\">"
				+"#{space1,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space2 != null\">"
				+"#{space2,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space3 != null\">"
				+"#{space3,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"space4 != null\">"
				+"#{space4,jdbcType=VARCHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.tiny.demo.entity.Product\">"
		+"	update product"
		+"	<set>"
		+"	<if test=\"name != null\">"
			+"name = #{name,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"title != null\">"
			+"title = #{title,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"creatdate != null\">"
			+"creatdate = #{creatdate,jdbcType=DATE},"
		+"	</if>"
		+"	<if test=\"modifydate != null\">"
			+"modifydate = #{modifydate,jdbcType=DATE},"
		+"	</if>"
		+"	<if test=\"saletotal != null\">"
			+"saletotal = #{saletotal,jdbcType=DOUBLE},"
		+"	</if>"
		+"	<if test=\"minpp != null\">"
			+"minpp = #{minpp,jdbcType=DOUBLE},"
		+"	</if>"
		+"	<if test=\"maxpp != null\">"
			+"maxpp = #{maxpp,jdbcType=DOUBLE},"
		+"	</if>"
		+"	<if test=\"describe != null\">"
			+"describe = #{describe,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"rate != null\">"
			+"rate = #{rate,jdbcType=DOUBLE},"
		+"	</if>"
		+"	<if test=\"cyclicity != null\">"
			+"cyclicity = #{cyclicity,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"state != null\">"
			+"state = #{state,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"star != null\">"
			+"star = #{star,jdbcType=DATE},"
		+"	</if>"
		+"	<if test=\"stop != null\">"
			+"stop = #{stop,jdbcType=DATE},"
		+"	</if>"
		+"	<if test=\"step != null\">"
			+"step = #{step,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space1 != null\">"
			+"space1 = #{space1,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space2 != null\">"
			+"space2 = #{space2,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space3 != null\">"
			+"space3 = #{space3,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"space4 != null\">"
			+"space4 = #{space4,jdbcType=VARCHAR},"
		+"	</if>"
		+"	</set>"
		+"	where productid = #{productid,jdbcType=VARCHAR}"
	+"	</update>";
	}
}